# -*- coding: utf-8 -*-
"""app_bitcoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxtdZJ4uZGN4n9NB8fopqy6Zx8S6L1y2
"""

# ==========================================
# INSTALACION DE LIBRERIAS
# ==========================================

# pip install streamlit yfinance matplotlib pandas numpy

# ==========================================
# LIBRERIAS
# ==========================================

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# ==========================================
# CONFIGURACION STREAMLIT
# ==========================================

st.set_page_config(
    page_title="Bitcoin Analytics",
    layout="wide"
)

# ==========================================
# IMAGEN JPG AL INICIO
# ==========================================

imagen = Image.open("bitcoin.jpg")
imagen = imagen.resize((500, 100))

st.image(
    imagen,
    use_container_width=True
)

# ==========================================
# TITULO
# ==========================================

st.title("Bitcoin Analytics Dashboard")

st.markdown("Análisis de soporte, ruptura y derivadas polinomiales para Bitcoin.")

# ==========================================
if ultimos_10_pendiente[-1] > 0:
    st.success("Tendencia reciente: ALCISTA (Ponte chingón)")
else:
    st.error("Tendencia reciente: BAJISTA (No seas necio)")
# ==========================================

# PARAMETROS
# ==========================================

ticker = st.sidebar.text_input(
    "Ticker",
    "BTC-USD"
)

periodo = st.sidebar.selectbox(
    "Periodo",
    ["6mo", "1y", "2y", "5y"],
    index=3
)

ventana = st.sidebar.slider(
    "Ventana Soporte",
    5,
    50,
    20
)

delta = st.sidebar.slider(
    "Ruptura %",
    0.001,
    0.05,
    0.01
)

# ==========================================
# DESCARGA DE DATOS
# ==========================================

df = yf.download(
    ticker,
    period=periodo,
    auto_adjust=True
)

# MultiIndex fix
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df.dropna()

# ==========================================
# VARIABLES
# ==========================================

close = df["Close"]

volume = df["Volume"]

# ==========================================
# SOPORTE
# ==========================================

df["Support"] = close.rolling(
    window=ventana
).min().shift(1)

# ==========================================
# VOLUMEN PROMEDIO
# ==========================================

df["Vol_mean"] = volume.rolling(
    window=ventana
).mean()

# ==========================================
# RUPTURA
# ==========================================

df["Breakdown"] = (
    (close < df["Support"] * (1 - delta)) &
    (volume > df["Vol_mean"])
)

# ==========================================
# GRAFICA SOPORTE
# ==========================================

fig1, (ax1, ax2) = plt.subplots(
    2,
    1,
    figsize=(14,8),
    sharex=True
)

# Precio
ax1.plot(
    df.index,
    close,
    label="Close",
    linewidth=2
)

ax1.plot(
    df.index,
    df["Support"],
    linestyle="--",
    label="Support"
)

ax1.scatter(
    df.index[df["Breakdown"]],
    close[df["Breakdown"]],
    color="red",
    label="Ruptura",
    zorder=5
)

ax1.set_title(f"Ruptura de Soporte - {ticker}")

ax1.legend()

ax1.grid(True)

# Volumen
ax2.bar(
    df.index,
    volume,
    label="Volumen"
)

ax2.plot(
    df.index,
    df["Vol_mean"],
    color="orange",
    label="Volumen Promedio"
)

ax2.legend()

ax2.grid(True)

plt.tight_layout()

st.pyplot(fig1)

# ==========================================
# DATOS BTC 1H
# ==========================================

btc = yf.download(
    ticker,
    period="50d",
    interval="1h"
)

# ==========================================
# CIERRE
# ==========================================

S = btc['Close']

Pf1 = S.to_numpy()

Pf2 = pd.DataFrame(
    Pf1,
    columns=['Close']
)

Pf2['Date'] = np.arange(
    1,
    len(Pf2) + 1
)

# ==========================================
# AJUSTE POLINOMIAL
# ==========================================

grado_polinomio = 3

coeficientes = np.polyfit(
    Pf2['Date'],
    Pf2['Close'],
    grado_polinomio
)

polinomio = np.poly1d(
    coeficientes
)

# ==========================================
# DERIVADA
# ==========================================

derivada = np.polyder(
    polinomio
)

# ==========================================
# AJUSTE
# ==========================================

x_fit = np.arange(
    1,
    len(Pf2) + 1
)

y_fit = polinomio(
    x_fit
)

pendiente = derivada(
    x_fit
)

# ==========================================
# ULTIMAS 10 HORAS
# ==========================================

ultimos_10_pendiente = pendiente[-10:]

ultimas_10_fechas = btc.index[-10:]

# ==========================================
# GRAFICA POLINOMIAL
# ==========================================

fig2 = plt.figure(figsize=(14,6))

plt.scatter(
    Pf2['Date'],
    Pf2['Close'],
    label='Precio BTC',
    s=10
)

plt.plot(
    x_fit,
    y_fit,
    color='red',
    label='Ajuste Polinomial'
)

plt.xlabel('Observación')

plt.ylabel('Precio')

plt.title('Ajuste Polinomial Bitcoin')

plt.legend()

plt.grid(True)

st.pyplot(fig2)

# ==========================================
# GRAFICA DERIVADA
# ==========================================

fig3 = plt.figure(figsize=(14,6))

plt.plot(
    ultimas_10_fechas,
    ultimos_10_pendiente,
    marker='o'
)

plt.axhline(
    y=0,
    linestyle='--'
)

plt.xlabel('Fecha')

plt.ylabel('Pendiente')

plt.title('Pendiente de la Derivada - Últimas 10 Horas')

plt.grid(True)

st.pyplot(fig3)

# ==========================================
# RESULTADOS
# ==========================================

st.subheader("(Derivada) Pendiente últimas 10 horas")

resultado = pd.DataFrame({
    "Fecha": ultimas_10_fechas,
    "Pendiente": np.round(
        ultimos_10_pendiente,
        4
    )
})

st.dataframe(resultado)

# ==========================================
# INTERPRETACION
# ==========================================

if ultimos_10_pendiente[-1] > 0:
    st.success("Tendencia reciente: ALCISTA (Ponte chingón)")
else:
    st.error("Tendencia reciente: BAJISTA (No seas necio)")
