# -*- coding: utf-8 -*-
"""app_bitcoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxtdZJ4uZGN4n9NB8fopqy6Zx8S6L1y2
"""

# ==========================================
# INSTALACION DE LIBRERIAS
# ==========================================

# pip install streamlit yfinance matplotlib pandas numpy

# ==========================================
# LIBRERIAS
# ==========================================

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from arch import arch_model
# ==========================================
# CONFIGURACION STREAMLIT
# ==========================================

st.set_page_config(
    page_title="Bitcoin Analytics",
    layout="wide"
)

# ==========================================
# IMAGEN JPG AL INICIO
# ==========================================

imagen = Image.open("bitcoin.jpg")
imagen = imagen.resize((500, 100))

st.image(
    imagen,
    use_container_width=True
)

# ==========================================
# TITULO
# ==========================================

st.title("Bitcoin Analytics Dashboard")

st.markdown("AI-Driven Bitcoin Analysis Through Support Detection, Breakout Structures, and Polynomial Derivatives")

# ==========================================
# ==========================================

# PARAMETROS
# ==========================================

ticker = st.sidebar.text_input(
    "Ticker",
    "BTC-USD"
)

periodo = st.sidebar.selectbox(
    "Periodo",
    ["6mo", "1y", "2y", "5y"],
    index=3
)

ventana = st.sidebar.slider(
    "Ventana Soporte",
    5,
    50,
    20
)

delta = st.sidebar.slider(
    "Ruptura %",
    0.001,
    0.05,
    0.01
)

# ==========================================
# DESCARGA DE DATOS  (II)
# ==========================================

df = yf.download(
    ticker,
    period=periodo,
    auto_adjust=True
)

# MultiIndex fix
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df.dropna()

# ==========================================
# VARIABLES
# ==========================================

close = df["Close"]

volume = df["Volume"]

# ==========================================
# SOPORTE
# ==========================================

df["Support"] = close.rolling(
    window=ventana
).min().shift(1)

# ==========================================
# VOLUMEN PROMEDIO
# ==========================================

df["Vol_mean"] = volume.rolling(
    window=ventana
).mean()

# ==========================================
# RUPTURA
# ==========================================

df["Breakdown"] = (
    (close < df["Support"] * (1 - delta)) &
    (volume > df["Vol_mean"])
)

# ==========================================
# GRAFICA SOPORTE
# ==========================================

fig1, (ax1, ax2) = plt.subplots(
    2,
    1,
    figsize=(14,8),
    sharex=True
)

# Precio
ax1.plot(
    df.index,
    close,
    label="Close",
    linewidth=2
)

ax1.plot(
    df.index,
    df["Support"],
    linestyle="--",
    label="Support"
)

ax1.scatter(
    df.index[df["Breakdown"]],
    close[df["Breakdown"]],
    color="red",
    label="Ruptura",
    zorder=5
)

ax1.set_title(f"Ruptura de Soporte - {ticker}")

ax1.legend()

ax1.grid(True)

# Volumen
ax2.bar(
    df.index,
    volume,
    label="Volumen"
)

ax2.plot(
    df.index,
    df["Vol_mean"],
    color="orange",
    label="Volumen Promedio"
)

ax2.legend()

ax2.grid(True)

plt.tight_layout()

st.pyplot(fig1)

# ==========================================
# DATOS BTC 60 DÍAS
# ==========================================

btc = yf.download(
    ticker,
    period="60d",
    interval="1d"
)

# ==========================================
# CIERRE
# ==========================================

S = btc['Close']

Pf1 = S.to_numpy()

Pf2 = pd.DataFrame(
    Pf1,
    columns=['Close']
)

Pf2['Date'] = np.arange(
    1,
    len(Pf2) + 1
)

# ==========================================
# AJUSTE POLINOMIAL
# ==========================================

grado_polinomio = 8

coeficientes = np.polyfit(
    Pf2['Date'],
    Pf2['Close'],
    grado_polinomio
)

polinomio = np.poly1d(
    coeficientes
)

# ==========================================
# DERIVADA
# ==========================================

derivada = np.polyder(
    polinomio
)

# ==========================================
# AJUSTE
# ==========================================

x_fit = np.arange(
    1,
    len(Pf2) + 1
)

y_fit = polinomio(
    x_fit
)

pendiente = derivada(
    x_fit
)

# ==========================================
# ULTIMAS 60 días
# ==========================================

ultimos_10_pendiente = pendiente[-5:]

ultimas_10_fechas = btc.index[-5:]

# ==========================================
# GRAFICA POLINOMIAL
# ==========================================

fig2 = plt.figure(figsize=(14,6))

plt.scatter(
    Pf2['Date'],
    Pf2['Close'],
    label='Precio BTC',
    s=10
)
# Último dato en verde
plt.scatter(
    Pf2['Date'].iloc[-1],
    Pf2['Close'].iloc[-1],
    color='#00FF00',
    s=80,
    label='Último dato'
)
plt.plot(
    x_fit,
    y_fit,
    color='red',
    label='Ajuste Polinomial'
)

plt.xlabel('Observación')

plt.ylabel('Precio')

plt.title('Ajuste Polinomial Bitcoin')

plt.legend()

plt.grid(True)

st.pyplot(fig2)

# ==========================================
###################### AHÍ
####   NUEVO CÓDIGO  #########
#############################
btc = yf.download(
    ticker,
    period="5d",
    interval="1h"
)

# ==========================================
# CIERRE
# ==========================================

S = btc['Close']

Pf1 = S.to_numpy()

Pf2 = pd.DataFrame(
    Pf1,
    columns=['Close']
)

Pf2['Date'] = np.arange(
    1,
    len(Pf2) + 1
)

# ==========================================
# AJUSTE POLINOMIAL
# ==========================================

grado_polinomio = 8

coeficientes = np.polyfit(
    Pf2['Date'],
    Pf2['Close'],
    grado_polinomio
)

polinomio = np.poly1d(
    coeficientes
)

# ==========================================
# DERIVADA
# ==========================================

derivada = np.polyder(
    polinomio
)

# ==========================================
# AJUSTE
# ==========================================

x_fit = np.arange(
    1,
    len(Pf2) + 1
)

y_fit = polinomio(
    x_fit
)

pendiente = derivada(
    x_fit
)

# ==========================================
# BANDAS DE RUPTURA
# ==========================================

residuos = Pf2['Close'].values - y_fit

desv = np.std(
    residuos
)

factor_banda = 2

banda_superior = (
    y_fit +
    factor_banda * desv
)

banda_inferior = (
    y_fit -
    factor_banda * desv
)

# ==========================================
# ULTIMAS 10 HORAS
# ==========================================

ultimos_10_pendiente = pendiente[-10:]

ultimas_10_fechas = btc.index[-10:]

# ==========================================
# DETECCIÓN DE RUPTURA BAJISTA
# ==========================================

precio_actual = Pf2['Close'].iloc[-1]

banda_inferior_actual = banda_inferior[-1]

ruptura_bajista = (
    precio_actual <
    banda_inferior_actual
)

# ==========================================
# GRAFICA POLINOMIAL
# ==========================================

fig2 = plt.figure(
    figsize=(14,6)
)

plt.scatter(
    Pf2['Date'],
    Pf2['Close'],
    label='Precio BTC',
    s=10
)

# Último dato
plt.scatter(
    Pf2['Date'].iloc[-1],
    Pf2['Close'].iloc[-1],
    color='#00FF00',
    s=80,
    label='Último dato'
)

# Curva polinomial
plt.plot(
    x_fit,
    y_fit,
    color='red',
    linewidth=2,
    label='Ajuste Polinomial'
)

# Banda superior
plt.plot(
    x_fit,
    banda_superior,
    '--',
    color='blue',
    linewidth=1.5,
    label='Banda Superior'
)

# Banda inferior
plt.plot(
    x_fit,
    banda_inferior,
    '--',
    color='orange',
    linewidth=2,
    label='Banda Ruptura Inferior'
)

# Señal de ruptura bajista
if ruptura_bajista:

    plt.scatter(
        Pf2['Date'].iloc[-1],
        precio_actual,
        color='black',
        marker='v',
        s=200,
        label='RUPTURA BAJISTA'
    )

plt.xlabel(
    'Observación'
)

plt.ylabel(
    'Precio'
)

plt.title(
    'Ajuste Polinomial Bitcoin con Banda de Ruptura'
)

plt.legend()

plt.grid(
    True
)

st.pyplot(
    fig2
)

# ==========================================
# ESTADO DE LA RUPTURA
# ==========================================

st.subheader(
    "Estado de Banda Inferior"
)

col1, col2 = st.columns(2)

with col1:
    st.metric(
        "Precio Actual",
        f"${precio_actual:,.2f}"
    )

with col2:
    st.metric(
        "Banda Inferior",
        f"${banda_inferior_actual:,.2f}"
    )

if ruptura_bajista:

    st.error(
        "🔴 RUPTURA BAJISTA ACTIVADA"
    )

else:

    distancia = (
        (precio_actual - banda_inferior_actual)
        / banda_inferior_actual
    ) * 100

    st.success(
        f"🟢 Sin ruptura bajista. Distancia a banda inferior: {distancia:.2f}%"
    )

##### FIN DE NUEVO CÓDIGO  ######
#####################  AHÍ
######  El análisis precio
# ==========================================
# DATOS BTC 1H
# ==========================================

btc = yf.download(
    ticker,
    period="5d",
    interval="1h"
)

# ==========================================
# CIERRE
# ==========================================

S = btc['Close']

Pf1 = S.to_numpy()

Pf2 = pd.DataFrame(
    Pf1,
    columns=['Close']
)

Pf2['Date'] = np.arange(
    1,
    len(Pf2) + 1
)

# ==========================================
# AJUSTE POLINOMIAL
# ==========================================

grado_polinomio = 8

coeficientes = np.polyfit(
    Pf2['Date'],
    Pf2['Close'],
    grado_polinomio
)

polinomio = np.poly1d(
    coeficientes
)

# ==========================================
# DERIVADA
# ==========================================

derivada = np.polyder(
    polinomio
)

# ==========================================
# AJUSTE
# ==========================================

x_fit = np.arange(
    1,
    len(Pf2) + 1
)

y_fit = polinomio(
    x_fit
)

pendiente = derivada(
    x_fit
)

# ==========================================
# ULTIMAS 10 HORAS
# ==========================================

ultimos_10_pendiente = pendiente[-10:]

ultimas_10_fechas = btc.index[-10:]

# ==========================================
# GRAFICA POLINOMIAL
# ==========================================

fig2 = plt.figure(figsize=(14,6))

plt.scatter(
    Pf2['Date'],
    Pf2['Close'],
    label='Precio BTC',
    s=10
)
# Último dato en verde
plt.scatter(
    Pf2['Date'].iloc[-1],
    Pf2['Close'].iloc[-1],
    color='#00FF00',
    s=80,
    label='Último dato'
)
plt.plot(
    x_fit,
    y_fit,
    color='red',
    label='Ajuste Polinomial'
)

plt.xlabel('Observación')

plt.ylabel('Precio')

plt.title('Ajuste Polinomial Bitcoin')

plt.legend()

plt.grid(True)

st.pyplot(fig2)

# ==========================================
# GRAFICA DERIVADA
# ==========================================

fig3 = plt.figure(figsize=(14,6))

plt.plot(
    ultimas_10_fechas,
    ultimos_10_pendiente,
    marker='o'
)

plt.axhline(
    y=0,
    linestyle='--'
)

plt.xlabel('Fecha')

plt.ylabel('Pendiente')

plt.title('Pendiente de la Derivada - Últimas 10 Horas')

plt.grid(True)

st.pyplot(fig3)

# ==========================================
# RESULTADOS
# ==========================================

st.subheader("(Derivada) Pendiente últimas 10 horas")

resultado = pd.DataFrame({
    "Fecha": ultimas_10_fechas,
    "Pendiente": np.round(
        ultimos_10_pendiente,
        4
    )
})

st.dataframe(resultado)

# ==========================================
# INTERPRETACION
# ==========================================

if ultimos_10_pendiente[-1] > 0:
    st.success("Tendencia reciente: ALCISTA (Ponte chingón, aprovecha que las cervezas no se pagan solas.)")
else:
    st.error("Tendencia reciente: BAJISTA (No seas pinche necio, mejor lee Poesía)")


##############################
#### GARCH  ########

st.subheader("Volatilidad GARCH(1,1)")

#====================================
# Descarga
#====================================

ticker = "BTC-USD"

data = yf.download(
    ticker,
    period="1y",
    interval="1d",
    progress=False
)

if data.empty:
    st.error("No fue posible descargar datos.")
    st.stop()

#====================================
# Precio de cierre
#====================================

close = data["Close"]

# Convertir a DataFrame si sólo existe un activo
if isinstance(close, pd.Series):
    close = close.to_frame(name=ticker)

#====================================
# Rendimientos logarítmicos
#====================================

returns = np.log(close / close.shift(1)).dropna()

#====================================
# Modelo GARCH
#====================================

vol_dict = {}

for col in returns.columns:

    model = arch_model(
        returns[col],
        mean="Zero",
        vol="GARCH",
        p=1,
        q=1,
        dist="normal"
    )

    result = model.fit(disp="off")

    vol_dict[col] = result.conditional_volatility

vol_df = pd.DataFrame(vol_dict)

#====================================
# Gráfico
#====================================

fig, ax = plt.subplots(figsize=(12,5))

for col in vol_df.columns:
    ax.plot(
        vol_df.index,
        vol_df[col] * 100,
        label=col
    )

ax.set_title("Volatilidad condicional GARCH(1,1)")
ax.set_xlabel("Fecha")
ax.set_ylabel("Volatilidad (%)")
ax.grid(True)
ax.legend()

st.pyplot(fig)

#====================================
# Mostrar datos
#====================================

st.dataframe(vol_df.tail())
#### GARCH  ########
# --- Personalización de diseño ---
# --- Personalización de diseño ---
st.markdown("""
<style>

    /* Fondo principal */
    .stApp {
        background-color: #0E1117;
        color: #FFFFFF;
    }

    /* Sidebar */
    section[data-testid="stSidebar"] {
        background-color: #161B22;
    }

    /* Texto general */
    html, body, [class*="css"]  {
        color: #FAFAFA;
    }

    /* Títulos */
    h1, h2, h3, h4 {
        color: #00C897;
    }

    /* Botones */
    .stButton>button {
        background-color: #00C897;
        color: white;
        border-radius: 10px;
        border: none;
        padding: 0.5em 1em;
    }

    .stButton>button:hover {
        background-color: #00E6A0;
        color: black;
    }

    /* Inputs */
    .stTextInput>div>div>input {
        background-color: #262730;
        color: white;
    }

    /* Selectbox */
    .stSelectbox>div>div {
        background-color: #262730;
        color: white;
    }

    /* Dataframe */
    .stDataFrame {
        background-color: #161B22;
    }

    /* Métricas */
    div[data-testid="metric-container"] {
        background-color: #161B22;
        border: 1px solid #00C897;
        padding: 10px;
        border-radius: 10px;
    }

</style>
""", unsafe_allow_html=True)


# ==========================================
# FASE LUNAR DEL DÍA
# ==========================================

st.markdown("---")

st.subheader("Fase Lunar Actual")

st.image(
    "https://www.lunopia.com/es/mod/moon.png?bg=1&fg=@ffffff&date=true&percent=true&phase=true&size=400",
    caption="Fase Lunar del Día",
    width=200
)

st.markdown(
    """
    <center>
        <small>
        Imagen actualizada automáticamente según la fecha actual.
        </small>
    </center>
    """,
    unsafe_allow_html=True
)
